version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
  build:
    commands:
      - make CXX=g++-7 CC=gcc-7 NEEDS_PTHREAD=TRUE
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - libUtility.a
    - UtilityTests.out
    - Log.txt
