version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y build-essential
      - g++ --version
      - apt-get install -y software-properties-common
      - apt-get update -y
      - apt-get upgrade -y
      - apt-get dist-upgrade -y || echo CANT DO dist-upgrade!
      - apt-get full-upgrade -y || apt-get full-upgrade || echo CANT DO full-upgrade!
      - add-apt-repository ppa:ubuntu-toolchain-r/test -y || echo CANT ADD REPO!
      - apt-get install -y libisl15 || echo CANT INSTALL libisl15!
      - apt-get install -y cpp-7 || echo CANT INSTALL cpp-7!
      - apt-get update -y
      - apt-get upgrade -y
      - apt-get install -y gcc-7 g++-7
      - g++ --version
      - g++-7 --version || echo CANT QUERY g++-7!
      - apt-get install -y libcurl3
      - apt-get install -y libboost-all-dev
  build:
    commands:
      - ls
      - make -j 8 CXX=g++-7 || make -j 8 CXX=g++
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - libUtility.a
    - UtilityTests.out
    - Log.txt
